# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'SKNetworkRequestDemo' do
    
pod 'AFNetworking', '~> 4.0'
pod 'YYModel', '~> 1.0.3'
pod 'Realm', '~> 3.0.2'
pod 'Masonry', '~> 1.1.0'
pod 'SKNetworkRequest', :path => '../'

end

